"""
Database Models for AI Storybook Generator

This module defines the SQLAlchemy ORM models for persisting stories
and their associated media in a SQLite database.

The database schema supports:
- Story metadata (title, prompts, text, timestamps)
- Interview personalization data (Q&A pairs)
- Asset references (audio narration, illustrations)
- One-to-many relationships (story → multiple images)

Author: Robert Moore
Date: January 2026
"""

from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import uuid

# SQLAlchemy database instance (initialized in app.py)
db = SQLAlchemy()


class Story(db.Model):
    """
    Main story model - represents a complete generated story.
    
    Each story is stored with:
    - Unique UUID for file system organization
    - Both original and enhanced prompts (for interview mode)
    - Complete story text
    - References to audio and image files
    - Timestamp for sorting and display
    
    The UUID is used to create a unique folder structure:
    static/stories/<uuid>/images/ and static/stories/<uuid>/audio/
    
    Relationships:
        images (StoryImage[]): One-to-many relationship with story images
    """
    __tablename__ = 'stories'
    
    # Primary key
    id = db.Column(db.Integer, primary_key=True)
    
    # Unique identifier for file organization
    uuid = db.Column(db.String(36), unique=True, nullable=False, default=lambda: str(uuid.uuid4()))
    
    # Story content
    title = db.Column(db.String(200), nullable=False)
    prompt = db.Column(db.Text, nullable=False)  # Final prompt used for generation
    original_prompt = db.Column(db.Text, nullable=True)  # Original prompt before interview (if applicable)
    interview_data = db.Column(db.Text, nullable=True)  # JSON string of Q&A pairs from interview
    story_text = db.Column(db.Text, nullable=False)  # Complete story text including title
    
    # Media references (relative paths from static/)
    audio_filename = db.Column(db.String(200), nullable=True)  # Path to MP3 narration file
    
    # Metadata
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationships
    images = db.relationship(
        'StoryImage', 
        backref='story', 
        lazy=True, 
        cascade='all, delete-orphan',  # Delete images when story is deleted
        order_by='StoryImage.page_number'  # Maintain page order
    )
    
    def __repr__(self):
        """String representation for debugging."""
        return f'<Story {self.uuid}: {self.title}>'
    
    @property
    def first_image(self):
        """
        Get the first image for thumbnail display in anthology.
        
        Returns:
            StoryImage: First image object, or None if no images exist
        """
        if self.images:
            return self.images[0]
        return None
    
    @property
    def story_folder(self):
        """
        Get the relative folder path for this story's assets.
        
        Returns:
            str: Folder path (e.g., 'stories/abc123-uuid...')
        """
        return f'stories/{self.uuid}'


class StoryImage(db.Model):
    """
    Individual story illustration model.
    
    Each story can have multiple images (typically 8-12, one per paragraph).
    Images are generated by DALL-E 3 and stored in the story's folder.
    
    The page_number field maintains the order of images as they appear
    in the story, allowing them to be interspersed with text correctly.
    
    Foreign Key:
        story_id: Links to parent Story record
    """
    __tablename__ = 'story_images'
    
    # Primary key
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign key to parent story
    story_id = db.Column(db.Integer, db.ForeignKey('stories.id'), nullable=False)
    
    # Image data
    image_filename = db.Column(db.String(200), nullable=False)  # Relative path from static/
    page_number = db.Column(db.Integer, nullable=False)  # Order in story (0-indexed)
    
    def __repr__(self):
        """String representation for debugging."""
        return f'<StoryImage {self.page_number} for Story {self.story_id}>'
